### PR TITLE
TEIID-4629: Complete DDL Syntax based VDB development

### PR DESCRIPTION
**Pull request by rareddy**

### CODE REVIEW

**Comment by shawkins** [comment]
Looks like a good start.  I'm ok with a new guide, but it seems like all the material should be in one place and we'll link as appropriate.  Do you want me make some changes?

**Comment by rareddy** [comment]
My idea was to get the relevant documents moved into one space, and delete the duplicate once this accepted. Sure you can make changes, or if you see bigger context missing let me know, I will add on it. First step I wanted make sure, I am going in right direction, looks like you agree.

**Comment by shawkins** [comment]
Let me take a pass through this.  We need to leave in place more about the xml way of doing things for at least the 9.2 release, then we can deprecate if desired for 9.3.  Also I'm going to combine things back into just the reference.  If we want to create a separate VDB reference, then we should consider pulling the translator pages in as well.

**Comment by rareddy** [comment]
I do not think I added any deprecation anywhere, but I added a recommendation which we can remove. I can add both XML version side by side the DDL semantics. But I think we should keep the separate document. once this is merged, then I can move the translators .

**Comment by shawkins** [comment]
Here's what it could look like consolidated in a prominent place under the reference - https://github.com/shawkins/teiid-documents/

The only thing that doesn't follow the structure is having the xml definition of data roles in the security guide.

**Comment by rareddy** [comment]
Looks good, one thing I was going for is having all the DDL constructs in single page,  but have references to their respective XML/DDL pages, now they are divided on xml/ddl lines.

**Comment by shawkins** [comment]
Do you want me to go ahead and push this, or do you want to take another pass?

**Comment by rareddy** [comment]
Push it, I am sure we will be keep adding to this. Thanks.

**Pull request closed without merging**
