### PR TITLE
Fix dv reference build

### PR DESCRIPTION
**Pull request by fbolton**
With these fixes, it is possible to build the Data Virtualization Reference downstream for the first time. @shawkins Can you take a look at this and check that the updates are Ok?

@roldanbob FYI

### CODE REVIEW

**Comment by shawkins** [comment]
The only issue would be with r_bnf-for-sql-grammar.adoc as it's auto generated.  Can you describe what should be different there?

**Comment by fbolton** [comment]
@shawkins The issue with `r_bnf-for-sql-grammar.adoc` is that some of the cross-reference links are referencing non-existent anchor IDs. In particular, the following anchor IDs do not exist in the BNF chapter:
```
usage_explainCommand
usage_procedureBodyCommand
usage_callableStatement
```
Our downstream build system has zero tolerance for broken cross-references, so these broken links cause our build to fail downstream. Incidentally, these links are also broken in the upstream documentation.

**Comment by shawkins** [comment]
I'll correct the generation logic so that there's an entry in the cross reference.

**Comment by fbolton** [comment]
@shawkins Is it ok to merge this PR now? If you prefer, I can modify this PR to undo the changes to the `r_bnf-for-sql-grammar.adoc` file. But it probably does not matter much either way, because those changes will get clobbered next time you regenerate the file.

**Comment by fbolton** [comment]
@shawkins Ok, I just rebased this PR to resolve the conflicts with your updates to the `r_bnf-for-sql-grammar.adoc` file.

**Comment by shawkins** [comment]
Thanks, I think we're good now.  I'm keeping your changes in sync with the 7.6-13.0.x branch as well.

**Pull request merged**
